#!/usr/bin/env python3
"""Thin wrapper — real logic lives in ~/.claude/skills/_shared/extract_transcript.py.

This wrapper exists for backward compatibility so commands like
`python ~/.claude/skills/self-improving-agent/scripts/extract_transcript.py --all`
keep working.

**Do NOT edit this file.** Edit the shared copy and this wrapper stays thin.
The shared copy is also referenced by neat-freak — both skills use the same
byte-identical logic, so version drift is impossible.

Shared source of truth: ~/.claude/skills/_shared/extract_transcript.py
"""
import os
import sys

_shared = os.path.abspath(
    os.path.join(os.path.dirname(__file__), "..", "..", "_shared", "extract_transcript.py")
)
exec(open(_shared, encoding="utf-8").read(), {"__name__": "__main__", "__file__": _shared})
